### ISSUE TITLE
React Native Modal not working inside RNWindowView

### ISSUE THREAD

**Issue by mistenkt** [WoLewicki/react-native-window-view#1]
Unable to show the `Modal` component from `react-native` on this layer. Throws exception when toggling visibility.

![image](https://user-images.githubusercontent.com/76615/117134985-a3402b00-ada6-11eb-99ec-26e41b9bd380.png)

Not sure if this is something that can be fixed in this package or we just need to create our own modal component to use on this layer.

These modals work fine outside `RNWindowView` but then cannot be overlayed on a modal screen unless we add it to the same layer.

**Comment by WoLewicki** [comment]
You mean you want to render a modal inside the `RNWindowView`? If so, it is not possible since it is not connected to any view controller. What is a use-case for such thing? `RNWindowView` is meant to display some small notifications/alerts on top of the view hierarchy. It may be possible to assign a view controller to the view, but I am not sure if it is the use-case for this library.

**Comment by mistenkt** [comment]
Use case would be same as toasts, loaders and such. We also use a centralised modal component. But if this is a limitation in RNWindowView we can just rewrite it to not sure the RN modal component and make our own. Thanks for the reply

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
