### ISSUE TITLE
Expo config plug-in 

### ISSUE THREAD

**Issue by nandorojo** [WoLewicki/react-native-window-view#10]
The readme states:

> To make the compoent stay on top even after pushing modals, you need to add the following code to your appDelegate.m

It would be great to add a config plug-in to this package that does this for you in Expo apps. This would improve the DX a lot, and it would allow managed Expo apps to use it.

**Comment by WoLewicki** [comment]
I think it is no longer necessary since after some discussion we decided to move this component into `react-native-screens` repo: https://github.com/software-mansion/react-native-screens/pull/1096. Also, the problem with adding things to `AppDelegate.m` was resolved by adding an extension of `UIWindow`. I'll make a quick PR with the same thing in this repo. I think we can close it then?

**Comment by nandorojo** [comment]
Sounds good! Glad to hear it’ll be in screens.
